/*
 * Copyright (c) 2018 Machine Zone Inc. All rights reserved.
 */
package org.apache.spark.ml.feature.parallel

import org.apache.spark.ml.Model
import org.apache.spark.ml.feature.{StandardScaler, StandardScalerModel, StandardScalerParams}
import org.apache.spark.ml.param.parallel.HasInputOutputCols
import org.apache.spark.ml.util.Identifiable

/**
  * ParallelStandardScaler
  *
  * [[StandardScaler]] that can operate on multiple input columns.
  *
  * @author belbis
  * @since 1.0.0
  */
class ParallelStandardScaler(override val uid: String)
  extends ParallelEstimator[ParallelStandardScalerModel, StandardScalerModel]
    with HasInputOutputCols with StandardScalerParams {

  // NOTE: uid must be defined in the constructor or you will see errors a la
  // https://issues.apache.org/jira/browse/SPARK-12606
  def this() = this(Identifiable.randomUID("ParallelStandardScaler"))

  /**
    * createStage
    *
    * Create new instance of [[StandardScaler]].
    *
    * @param inputColumn
    * @return
    */
  override def createStage(inputColumn: String): StandardScaler = {
    new StandardScaler()
      .setInputCol(inputColumn)
      .setOutputCol($(outputCols)($(inputCols).indexOf(inputColumn)))
      .setWithMean($(withMean))
      .setWithStd($(withStd))
  }

  /**
    * createModel
    *
    * Create new instance of [[ParallelStandardScalerModel]].
    *
    * @param models
    * @return
    */
  override def createModel(models: Map[String, StandardScalerModel]):
  ParallelStandardScalerModel = {
    new ParallelStandardScalerModel()
      .setInputCols($(inputCols))
      .setStages(models)
  }

}

/**
  * ParallelStandardScalerModel
  *
  * [[Model]] generated by falling #fit() on [[ParallelStandardScaler]].
  *
  * @param uid
  * @author belbis
  * @since 1.0.0
  */
class ParallelStandardScalerModel(override val uid: String)
  extends Model[ParallelStandardScalerModel] with ParallelModel[StandardScalerModel] {

  // NOTE: uid must be defined in the constructor or you will see errors a la
  // https://issues.apache.org/jira/browse/SPARK-12606
  def this() = this(Identifiable.randomUID("ParallelStandardScalerModel"))

}
